name: audio_manager_app
description: Um aplicativo de exemplo para gerenciar áudios com BLoC em Flutter.

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  assets_audio_player: ^3.1.1
  bloc_test: ^9.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.0.0

  # Adicione qualquer ativo (áudios, imagens, etc.) que você precise acessar no aplicativo
flutter:
  uses-material-design: true
  assets:
    - assets/a-long-way-166385.mp3
    - assets/dark-mystery-trailer-taking-our-time-131566.mp3
    - assets/leonell-cassio-the-blackest-bouquet-118766.mp3
    - assets/risk-136788.mp3
